services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust

  localai:
    image: localai/localai:latest-aio-cpu
    command: ["/usr/bin/local-ai" ]
    ports:
      - 8081:8080
    environment:
      - MODELS_PATH=/build/models
      - LOCALAI_THREADS=4
      - LOCALAI_PARALLEL_REQUESTS=false
      - DEBUG=true
    volumes:
      - ./localai:/build/models

  ollama:
    image: ollama/ollama
    ports:
      - 8082:11434
    volumes:
      - ./ollama:/root/.ollama