services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust

  localai:
    image: quay.io/go-skynet/local-ai:v2.22.1
    command: ["/usr/bin/local-ai" ]
    ports:
      - 8888:8080
    environment:
      - MODELS_PATH=/build/models
      - DEBUG=false
      - LOCALAI_THREADS=14
      - LLAMACPP_PARALLEL=1
      - LOCALAI_PARALLEL_REQUESTS=false
    volumes:
      - ./models:/build/models